# -*- coding":  utf-8 -*-

def bairro_sp_dic():
    bairros = {
        "0": "Fora do Estado de S\xc3\xa2o Paulo",
        "1": "Artur Alvim",
        "2": "Agua Branca",
        "3": "Agua Fria",
        "4": "Agua Funda",
        "5": "Agua Rasa",
        "6": "Altos de Vila Prudente",
        "7": "Aclimacao",
        "8": "Americanopolis",
        "9": "Anhanguera",
        "10": "Aricanduva",
        "11": "Alto da Lapa",
        "12": "Alto da Mooca",
        "13": "Alto do Pari",
        "14": "Alto de Pinheiros",
        "15": "Alto da Riviera",
        "16": "Avenida Aguas Espraiadas",
        "17": "Bela Alianca",
        "18": "Barro Branco",
        "19": "Barra Funda",
        "20": "Brooklin Novo",
        "21": "Bom Retiro",
        "22": "Bela Vista",
        "23": "Balne\xc3\xa1rio Dom Carlos",
        "24": "Balne\xc3\xa1rio Mar Paulista",
        "25": "Balne\xc3\xa1rio S\xc3\xa2o Francisco",
        "26": "Balne\xc3\xa1rio S\xc3\xa2o Jose",
        "27": "Baronesa",
        "28": "Barragem",
        "29": "Belem",
        "30": "Belenzinho",
        "31": "Boacava",
        "32": "Borore",
        "33": "Bortolandia",
        "34": "Br\xc3\xa1s",
        "35": "Brasilandia",
        "36": "Brooklin Paulista",
        "37": "Bosque da Saude",
        "38": "Burgo Paulista",
        "39": "Butanta",
        "40": "Cidade Antonio Estevao de Carvalh",
        "41": "Cidade Ademar",
        "42": "City America",
        "43": "Cidade Auxiliadora",
        "44": "Cidade dos Bandeirantes",
        "45": "Clube Campestre de S\xc3\xa2o Paulo",
        "46": "Cidade Centenario",
        "47": "Cerqueira Cesar",
        "48": "Cidade Continental",
        "49": "Clube de Campo Kibom",
        "50": "Cidade D'abril",
        "51": "Cidade Domitila",
        "52": "Cidade Dutra",
        "53": "Campos Eliseos",
        "54": "Capao da Embira",
        "55": "Clube dos Funcionarios Publicos C",
        "56": "Cidade Fim de Semana",
        "57": "Casa Grande",
        "58": "Cidade Ipava",
        "59": "Cidade Jardim",
        "60": "Cidade Julia",
        "61": "Cidade Kemel",
        "62": "Cidade Leonor",
        "63": "Cidade Lider",
        "64": "Cidade Mae do Ceu",
        "65": "Cidade Munhoz Junior",
        "66": "Cipo do Meio",
        "67": "Chora Menino",
        "68": "Cidade Moncoes",
        "69": "Cidade Nova Heliopolis",
        "70": "Cidade Nitro Operaria",
        "71": "Cidade Nitro Quimica",
        "72": "Cidade Nova S\xc3\xa2o Miguel",
        "73": "Cidade Nautica",
        "74": "Cidade Patriarca",
        "75": "Cidade Popular",
        "76": "Capao Redondo",
        "77": "Cidade S\xc3\xa2o Francisco",
        "78": "Cidade S\xc3\xa2o Mateus",
        "79": "Cidade S\xc3\xa2o Miguel",
        "80": "Cidade Satelite Santa Barbara",
        "81": "Cidade Satelite",
        "82": "Capela do Socorro",
        "83": "Cidade Tiradentes",
        "84": "Casa Verde Alta",
        "85": "Casa Verde Baixa",
        "86": "Casa Verde Media",
        "87": "Cidade Vargas",
        "88": "Casa Verde",
        "89": "Cachoeirinha",
        "90": "Cambuci",
        "91": "Campininha",
        "92": "Cangaiba",
        "93": "Caninde",
        "94": "Cantareira",
        "95": "Carandiru",
        "96": "Carrao",
        "97": "Catumbi",
        "98": "Caxingui",
        "99": "Centro",
        "100": "Ch\xc3\xa1cara Seis de Outubro",
        "101": "Ch\xc3\xa1cara Bandeirantes",
        "102": "Ch\xc3\xa1cara Belenzinho",
        "103": "Ch\xc3\xa1cara Bosque do Sul",
        "104": "Ch\xc3\xa1cara Cruzeiro do Sul",
        "105": "Ch\xc3\xa1cara California",
        "106": "Ch\xc3\xa1cara Cocaia",
        "107": "Ch\xc3\xa1cara das Corujas",
        "108": "Ch\xc3\xa1cara Dona Olivia",
        "109": "Ch\xc3\xa1cara do Encosto",
        "110": "Ch\xc3\xa1cara da Enseada",
        "111": "Ch\xc3\xa1cara Figueira Grande",
        "112": "Ch\xc3\xa1cara Flora",
        "113": "Ch\xc3\xa1cara Florida",
        "114": "Ch\xc3\xa1cara Gaivota",
        "115": "Ch\xc3\xa1cara Inglesa",
        "116": "Ch\xc3\xa1cara Itaim",
        "117": "Ch\xc3\xa1cara Japonesa",
        "118": "Ch\xc3\xa1cara Jaragua",
        "119": "Ch\xc3\xa1cara Maria Trindade",
        "120": "Ch\xc3\xa1cara Mafalda",
        "121": "Ch\xc3\xa1cara Meyer",
        "122": "Ch\xc3\xa1cara Morro Alto",
        "123": "Ch\xc3\xa1cara Monte Alegre",
        "124": "Ch\xc3\xa1cara Monte Sol",
        "125": "Ch\xc3\xa1cara Nossa Senhora Aparecida",
        "126": "Ch\xc3\xa1cara Nossa Senhora do Bom Cons",
        "127": "Ch\xc3\xa1cara Nani",
        "128": "Ch\xc3\xa1cara Pouso Alegre",
        "129": "Ch\xc3\xa1cara das Paineiras",
        "130": "Ch\xc3\xa1cara Paiva",
        "131": "Ch\xc3\xa1cara das Palmeiras",
        "132": "Ch\xc3\xa1cara Pirajussara",
        "133": "Ch\xc3\xa1cara Santo Amaro",
        "134": "Ch\xc3\xa1cara Santo Antonio",
        "135": "Ch\xc3\xa1cara Sonho Azul",
        "136": "Ch\xc3\xa1cara Santa Etelvina",
        "137": "Ch\xc3\xa1cara Santo Hubertus",
        "138": "Ch\xc3\xa1cara S\xc3\xa2o Joao",
        "139": "Ch\xc3\xa1cara S\xc3\xa2o Luis",
        "140": "Ch\xc3\xa1cara Santa Maria",
        "141": "Ch\xc3\xa1cara S\xc3\xa2o Silvestre",
        "142": "Ch\xc3\xa1cara Santana",
        "143": "Ch\xc3\xa1cara Tres Meninas",
        "144": "Ch\xc3\xa1cara Tatuape",
        "145": "Ch\xc3\xa1cara Vista Alegre",
        "146": "Ch\xc3\xa1cara Vovo",
        "147": "Chapada",
        "148": "Conjunto dos Bancarios",
        "149": "Conjunto Habitacional a e Carvalh",
        "150": "Conjunto Habitacional Aguia de Ha",
        "151": "Conjunto Habitacional Barro Branc",
        "152": "Conjunto Habitacional Barro Branc",
        "153": "Conjunto Habitacional Brigadeiro",
        "154": "Conjunto Habitacional Brigadeiro",
        "155": "Conjunto Habitacional Barreira Gr",
        "156": "Conjunto Habitacional Castro Alve",
        "157": "Conjunto Habitacional Instituto A",
        "158": "Conjunto Habitacional Inacio Mont",
        "159": "Conjunto Habitacional Juscelino K",
        "160": "Conjunto Habitacional Jova Rural",
        "161": "Conjunto Habitacional Jardim S\xc3\xa2o",
        "162": "Conjunto Habitacional Jardim Sant",
        "163": "Conjunto Habitacional Jardim S\xc3\xa2o",
        "164": "Conjunto Habitacional Marechal Ma",
        "165": "Conjunto Habitacional Padre Jose",
        "166": "Conjunto Habitacional Padre Manoe",
        "167": "Conjunto Habitacional Padre Manoe",
        "168": "Conjunto Habitacional Pirajussara",
        "169": "Conjunto Habitacional Recanto dos",
        "170": "Conjunto Habitacional Santa Etelv",
        "171": "Conjunto Habitacional Santa Etelv",
        "172": "Conjunto Habitacional Santa Etelv",
        "173": "Conjunto Habitacional S\xc3\xadtio Carag",
        "174": "Conjunto Habitacional S\xc3\xadtio Conce",
        "175": "Conjunto Habitacional Teotonio Vi",
        "176": "Conjunto Habitacional Vila Nova C",
        "177": "Conjunto Promorar Estrada da Para",
        "178": "Conjunto Promorar Rio Claro",
        "179": "Conjunto Promorar Raposo Tavares",
        "180": "Conjunto Promorar S\xc3\xa2o Luis",
        "181": "Conjunto Promorar Sapopemba",
        "182": "Conjunto Promorar Vila Maria III",
        "183": "Conjunto Residencial Alpes do Jar",
        "184": "Conjunto Residencial Bandeirantes",
        "185": "Conjunto Residencial Butanta",
        "186": "Conjunto Residencial Elisio Teixe",
        "187": "Conjunto Residencial Ingai",
        "188": "Conjunto Residencial Jose Bonifac",
        "189": "Conjunto Residencial Jardim Canaa",
        "190": "Conjunto Residencial Morumbi",
        "191": "Conjunto Residencial Novo Pacaemb",
        "192": "Conjunto Residencial Prestes Maia",
        "193": "Conjunto Residencial Paraiso",
        "194": "Conjunto Residencial Pinheirinho",
        "195": "Conjunto Residencial Santa Maria",
        "196": "Conjunto Residencial Santa Terezi",
        "197": "Conjunto Residencial Salvador Tol",
        "198": "Conjunto Residencial S\xc3\xadtio Orator",
        "199": "Conjunto Residencial Vista Verde",
        "200": "Colonia",
        "201": "Consolacao",
        "202": "Copacabana",
        "203": "Campo Belo",
        "204": "Campo Grande",
        "205": "Campo Limpo",
        "206": "Cupece",
        "207": "Cursino",
        "208": "Engenheiro Goulart",
        "209": "Estancia Jaragua",
        "210": "Engenheiro Marsilac",
        "211": "Ermelino Matarazzo",
        "212": "Embu Mirim",
        "213": "Estancia Tangara",
        "214": "Engenheiro Trindade",
        "215": "Educandario",
        "216": "Eldorado",
        "217": "Embura",
        "218": "Estancia Mirim",
        "219": "Favela Vila Nova Jaguare",
        "220": "Fazenda Aricanduva",
        "221": "Fazenda Itaim",
        "222": "Fazenda Juta",
        "223": "Fazenda Morumbi",
        "224": "Ferreira",
        "225": "Freguesia do o",
        "226": "Furnas",
        "227": "Gleba do Pessego",
        "228": "Granja Julieta",
        "229": "Granja Nossa Senhora Aparecida",
        "230": "Grajau",
        "231": "Guacuri",
        "232": "Guaianazes",
        "233": "Guaiauna",
        "234": "Guapira",
        "235": "Guarapiranga",
        "236": "Guavirutuba",
        "237": "Horto Florestal",
        "238": "Higienopolis",
        "239": "Horto",
        "240": "Itaim Bibi",
        "241": "Itaim Paulista",
        "242": "Instituto de Previdencia",
        "243": "Ibirapuera",
        "244": "Iguatemi",
        "245": "Imirim",
        "246": "Indianopolis",
        "247": "Interlagos",
        "248": "Ipiranga",
        "249": "Itaberaba",
        "250": "Itaim",
        "251": "Itaquera",
        "252": "Itupu",
        "253": "Jose Bonifacio",
        "254": "Jabaquara",
        "255": "Jacana",
        "256": "Jaguare",
        "257": "Jaragua",
        "258": "Jardim do Colegio",
        "259": "Jardim Artur Alvim",
        "260": "Jardim Adhemar de Barros",
        "261": "Jardim Analia Franco",
        "262": "Jardim Ataliba Leonel",
        "263": "Jardim Ana Lucia",
        "264": "Jardim Ana Maria",
        "265": "Jardim America da Penha",
        "266": "Jardim Almeida Prado",
        "267": "Jardim Ana Rosa",
        "268": "Jardim das Acacias",
        "269": "Jardim Adelaide",
        "270": "Jardim Adelfiore",
        "271": "Jardim Adelia",
        "272": "Jardim Adutora",
        "273": "Jardim Aeroporto",
        "274": "Jardim Aida",
        "275": "Jardim Aimore",
        "276": "Jardim Aladim",
        "277": "Jardim dos Alamos",
        "278": "Jardim Albano",
        "279": "Jardim Alfredo",
        "280": "Jardim Almanara",
        "281": "Jardim Alpino",
        "282": "Jardim Alteza",
        "283": "Jardim do Alto",
        "284": "Jardim Alva",
        "285": "Jardim Alvarenga",
        "286": "Jardim Alvina",
        "287": "Jardim Alviverde",
        "288": "Jardim Alvorada",
        "289": "Jardim Alzira",
        "290": "Jardim Amalia",
        "291": "Jardim Amaralina",
        "292": "Jardim America",
        "293": "Jardim Ampliacao",
        "294": "Jardim Anchieta",
        "295": "Jardim Andarai",
        "296": "Jardim Angela",
        "297": "Jardim Angelina",
        "298": "Jardim Anhanguera",
        "299": "Jardim Antartica",
        "300": "Jardim Aparecida",
        "301": "Jardim Apura",
        "302": "Jardim Aracati",
        "303": "Jardim Arco-Iris",
        "304": "Jardim Aricanduva",
        "305": "Jardim Arize",
        "306": "Jardim Arizona",
        "307": "Jardim Arpoador",
        "308": "Jardim Assuncao",
        "309": "Jardim Alto Alegre",
        "310": "Jardim Alto Pedroso",
        "311": "Jardim Alto do Rio Bonito",
        "312": "Jardim Atibaia",
        "313": "Jardim Atlantico",
        "314": "Jardim Augusta",
        "315": "Jardim Augusto",
        "316": "Jardim Aurelia",
        "317": "Jardim Aurelio",
        "318": "Jardim Aurora",
        "319": "Jardim Avelino",
        "320": "Jardim Avenida",
        "321": "Jardim Bom Clima",
        "322": "Jardim Boa Esperanca",
        "323": "Jardim Borba Gato",
        "324": "Jardim Bom Pastor",
        "325": "Jardim Bom Refugio",
        "326": "Jardim Boa Sorte",
        "327": "Jardim Bandeirante",
        "328": "Jardim das Bandeiras",
        "329": "Jardim Bandeirantes",
        "330": "Jardim Barros",
        "331": "Jardim Bartira",
        "332": "Jardim Batalha",
        "333": "Jardim Beatriz",
        "334": "Jardim Bela Vista",
        "335": "Jardim Belaura",
        "336": "Jardim Belcito",
        "337": "Jardim Belem",
        "338": "Jardim Belgica",
        "339": "Jardim Benfica",
        "340": "Jardim Bibi",
        "341": "Jardim Bichinhos",
        "342": "Jardim Boa Vista",
        "343": "Jardim Bonfiglioli",
        "344": "Jardim Bonito",
        "345": "Jardim Botucatu",
        "346": "Jardim Brasil",
        "347": "Jardim Brasilia",
        "348": "Jardim Britania",
        "349": "Jardim Bronzato",
        "350": "Jardim Bosque do Sol",
        "351": "Jardim Buriti",
        "352": "Jardim Cercado da Estrada",
        "353": "Jardim Casa Grande",
        "354": "Jardim Cinco de Julho",
        "355": "Jardim Cedro do Libano",
        "356": "Jardim Casa Pintada",
        "357": "Jardim Cidade Pirituba",
        "358": "Jardim Capao Redondo",
        "359": "Jardim Clara Regina",
        "360": "Jardim Cabore",
        "361": "Jardim Cabucu",
        "362": "Jardim Cachoeira",
        "363": "Jardim Caguassu",
        "364": "Jardim Camara",
        "365": "Jardim Camargo",
        "366": "Jardim Cambara",
        "367": "Jardim das Camelias",
        "368": "Jardim da Campina",
        "369": "Jardim Campinas",
        "370": "Jardim do Campo",
        "371": "Jardim Campos",
        "372": "Jardim Capela",
        "373": "Jardim Capelinha",
        "374": "Jardim Caravelas",
        "375": "Jardim Carlu",
        "376": "Jardim do Carmo",
        "377": "Jardim Carolina",
        "378": "Jardim Carombe",
        "379": "Jardim Casablanca",
        "380": "Jardim Castelo",
        "381": "Jardim dos Cataldis",
        "382": "Jardim Catanduva",
        "383": "Jardim Catarina",
        "384": "Jardim Cecy I",
        "385": "Jardim Cecy II (Cod Bai - 01899)",
        "386": "Jardim Celeste",
        "387": "Jardim Celia",
        "388": "Jardim Centenario",
        "389": "Jardim Central",
        "390": "Jardim do Centro",
        "391": "Jardim Chester",
        "392": "Jardim Cibele",
        "393": "Jardim Cidalia",
        "394": "Jardim Cimobil",
        "395": "Jardim Clarice",
        "396": "Jardim Claudia",
        "397": "Jardim Cleide",
        "398": "Jardim Clelia",
        "399": "Jardim Climax",
        "400": "Jardim Cliper",
        "401": "Jardim Coimbra",
        "402": "Jardim Colegio",
        "403": "Jardim Colina",
        "404": "Jardim Colombo",
        "405": "Jardim Colonial",
        "406": "Jardim Colorado",
        "407": "Jardim Comercial",
        "408": "Jardim Concordia",
        "409": "Jardim da Conquista",
        "410": "Jardim Consorcio",
        "411": "Jardim Consupler",
        "412": "Jardim Copacabana",
        "413": "Jardim Cordeiro",
        "414": "Jardim Cotching",
        "415": "Jardim Cotiana",
        "416": "Jardim Cotinha",
        "417": "Jardim Campo dos Ferreiros",
        "418": "Jardim Campo Grande",
        "419": "Jardim Campo Limpo",
        "420": "Jardim Cristal",
        "421": "Jardim Cristalia",
        "422": "Jardim Cristina",
        "423": "Jardim Cruzeiro",
        "424": "Jardim Cupece",
        "425": "Jardim Dom Bosco",
        "426": "Jardim Dona Deolinda",
        "427": "Jardim Dom Fernando",
        "428": "Jardim Dom Jose",
        "429": "Jardim Dona Sinha",
        "430": "Jardim da Gloria",
        "431": "Jardim da Laranjeira",
        "432": "Jardim da Saude",
        "433": "Jardim D'abril",
        "434": "Jardim Dalmo",
        "435": "Jardim Damasceno",
        "436": "Jardim Danfer",
        "437": "Jardim das Laranjeiras",
        "438": "Jardim Daysy",
        "439": "Jardim Denyse",
        "440": "Jardim Deolinda",
        "441": "Jardim Dinorah",
        "442": "Jardim Diomar",
        "443": "Jardim Dionisio",
        "444": "Jardim do Divino",
        "445": "Jardim do Russo",
        "446": "Jardim Domitila",
        "447": "Jardim Donaria",
        "448": "Jardim dos Bichinhos",
        "449": "Jardim dos Pinheiros",
        "450": "Jardim Dracena",
        "451": "Jardim Drumond",
        "452": "Jardim Duprat",
        "453": "Jardim Elisa Maria",
        "454": "Jardim Engenheiro Visconti",
        "455": "Jardim Ester Yolanda",
        "456": "Jardim Edda",
        "457": "Jardim Edi",
        "458": "Jardim Edilene",
        "459": "Jardim Edith",
        "460": "Jardim Edwiges",
        "461": "Jardim Egle",
        "462": "Jardim Elba",
        "463": "Jardim Eledy",
        "464": "Jardim Eliana-a",
        "465": "Jardim Eliane",
        "466": "Jardim Elisio",
        "467": "Jardim Eliza",
        "468": "Jardim Elizabeth",
        "469": "Jardim Ellus",
        "470": "Jardim Elza",
        "471": "Jardim Emilia",
        "472": "Jardim Ernestina",
        "473": "Jardim Esmeralda",
        "474": "Jardim das Esmeraldas",
        "475": "Jardim Esperanca",
        "476": "Jardim dos Estados",
        "477": "Jardim Ester",
        "478": "Jardim Estrela",
        "479": "Jardim Etelvina",
        "480": "Jardim dos Eucaliptos",
        "481": "Jardim Europa",
        "482": "Jardim Eva",
        "483": "Jardim Everest",
        "484": "Jardim Figueira Grande",
        "485": "Jardim Faria Lima",
        "486": "Jardim Francisco Mentem",
        "487": "Jardim Florida Paulista",
        "488": "Jardim Fim de Semana",
        "489": "Jardim Felicidade",
        "490": "Jardim Fernandes",
        "491": "Jardim Flamingo",
        "492": "Jardim das Flores",
        "493": "Jardim Floresta",
        "494": "Jardim Fluminense",
        "495": "Jardim Fonte do Morumbi",
        "496": "Jardim Fonte S\xc3\xa2o Miguel",
        "497": "Jardim Franca",
        "498": "Jardim dos Francos",
        "499": "Jardim Franganielo",
        "500": "Jardim Fraternidade",
        "501": "Jardim Fujihara",
        "502": "Jardim Gilda Maria",
        "503": "Jardim Galli",
        "504": "Jardim Germania",
        "505": "Jardim Gianetti",
        "506": "Jardim Gilberto",
        "507": "Jardim Gloria",
        "508": "Jardim Gonzaga",
        "509": "Jardim das Gracas",
        "510": "Jardim Grimaldi",
        "511": "Jardim Guacuri",
        "512": "Jardim Guaianazes",
        "513": "Jardim Guairaca",
        "514": "Jardim Guanabara",
        "515": "Jardim Guanca",
        "516": "Jardim Guanhembu",
        "517": "Jardim Guapira",
        "518": "Jardim Guarani",
        "519": "Jardim Guarapiranga",
        "520": "Jardim Guarau",
        "521": "Jardim Guaruja",
        "522": "Jardim Guedala",
        "523": "Jardim Guiomar",
        "524": "Jardim Gustavo",
        "525": "Jardim Horizonte Azul",
        "526": "Jardim Haia do Carrao",
        "527": "Jardim Horto Florestal",
        "528": "Jardim Humberto Nastari",
        "529": "Jardim Hadad",
        "530": "Jardim Harmonia",
        "531": "Jardim Helena",
        "532": "Jardim Helga",
        "533": "Jardim Helian",
        "534": "Jardim Heliomar",
        "535": "Jardim Heloisa",
        "536": "Jardim Hercilia",
        "537": "Jardim Herculano",
        "538": "Jardim Herplin",
        "539": "Jardim Hipico",
        "540": "Jardim Humaita",
        "541": "Jardim Ida Guedes",
        "542": "Jardim Iae",
        "543": "Jardim Iara",
        "544": "Jardim Ibirapuera",
        "545": "Jardim Ibiratiba",
        "546": "Jardim Ibitirama",
        "547": "Jardim Icara",
        "548": "Jardim Icarai",
        "549": "Jardim Ideal",
        "550": "Jardim Iguatemi",
        "551": "Jardim Imbe",
        "552": "Jardim das Imbuias",
        "553": "Jardim Imperador",
        "554": "Jardim Imperial",
        "555": "Jardim Imperio",
        "556": "Jardim Indaia",
        "557": "Jardim Independencia",
        "558": "Jardim Inga",
        "559": "Jardim Internacional",
        "560": "Jardim Ipanema",
        "561": "Jardim Ipe",
        "562": "Jardim dos Ipes",
        "563": "Jardim Ipora",
        "564": "Jardim Iporanga",
        "565": "Jardim Iracema",
        "566": "Jardim Irapiranga",
        "567": "Jardim Irene",
        "568": "Jardim Iris",
        "569": "Jardim Itacolomi",
        "570": "Jardim Itaguacu",
        "571": "Jardim Itajai",
        "572": "Jardim Italia",
        "573": "Jardim Itamaraty",
        "574": "Jardim Itaoca",
        "575": "Jardim Itapemirim",
        "576": "Jardim Itapeva",
        "577": "Jardim Itapolis",
        "578": "Jardim Itapura",
        "579": "Jardim Itatiaia",
        "580": "Jardim Itatinga",
        "581": "Jardim Iva",
        "582": "Jardim Ivana",
        "583": "Jardim Ivete",
        "584": "Jardim Ivone",
        "585": "Jardim Joana D Arc",
        "586": "Jardim Jabaquara",
        "587": "Jardim Jacana",
        "588": "Jardim dos Jacarandas",
        "589": "Jardim Jamaica",
        "590": "Jardim Japao",
        "591": "Jardim Jaqueline",
        "592": "Jardim Jaragua",
        "593": "Jardim Jau",
        "594": "Jardim Jeriva",
        "595": "Jardim Joamar",
        "596": "Jardim Joao Xxiii",
        "597": "Jardim Joia",
        "598": "Jardim Jordao",
        "599": "Jardim Jua",
        "600": "Jardim Julieta",
        "601": "Jardim Jurema",
        "602": "Jardim Jussara",
        "603": "Jardim Kagohara",
        "604": "Jardim Kaj",
        "605": "Jardim Keralux",
        "606": "Jardim Kika",
        "607": "Jardim Kioto",
        "608": "Jardim Los Angeles",
        "609": "Jardim Lucio de Castro",
        "610": "Jardim Leonor Mendes de Barros",
        "611": "Jardim Leonidas Moreira",
        "612": "Jardim Lar S\xc3\xa2o Paulo",
        "613": "Jardim Lageado",
        "614": "Jardim do Lago",
        "615": "Jardim dos Lagos",
        "616": "Jardim Lallo",
        "617": "Jardim Laone",
        "618": "Jardim Lapena",
        "619": "Jardim Laranjal",
        "620": "Jardim Laranjeiras",
        "621": "Jardim Laura",
        "622": "Jardim Leila",
        "623": "Jardim Leme",
        "624": "Jardim Leni",
        "625": "Jardim Leonardo",
        "626": "Jardim Leonor",
        "627": "Jardim Leticia",
        "628": "Jardim Libano",
        "629": "Jardim Lice",
        "630": "Jardim Lider",
        "631": "Jardim Lideranca",
        "632": "Jardim Lidia",
        "633": "Jardim Lilah",
        "634": "Jardim Lisboa",
        "635": "Jardim Londrina",
        "636": "Jardim de Lorenzo",
        "637": "Jardim Lourdes",
        "638": "Jardim Luanda",
        "639": "Jardim Lucelia",
        "640": "Jardim Lucia",
        "641": "Jardim Luciana",
        "642": "Jardim Lucinda",
        "643": "Jardim Lugo",
        "644": "Jardim Luisa",
        "645": "Jardim Luso",
        "646": "Jardim Luzitania",
        "647": "Jardim Maria Amalia",
        "648": "Jardim Monte Belo",
        "649": "Jardim Maria Duarte",
        "650": "Jardim Maria Emilia",
        "651": "Jardim Maria Estela",
        "652": "Jardim Maria Fernandes",
        "653": "Jardim Maria Lucia",
        "654": "Jardim Maria Luiza",
        "655": "Jardim Maria Margarida",
        "656": "Jardim Maria Nazare",
        "657": "Jardim Marco Paulo",
        "658": "Jardim Morais Prado",
        "659": "Jardim Maria Rita",
        "660": "Jardim Maria Sampaio",
        "661": "Jardim Martins Silva",
        "662": "Jardim Maria Virginia",
        "663": "Jardim Mabel",
        "664": "Jardim Macedonia",
        "665": "Jardim Machado",
        "666": "Jardim Maggi",
        "667": "Jardim Maia",
        "668": "Jardim Malia I",
        "669": "Jardim Malia II",
        "670": "Jardim dos Manacas",
        "671": "Jardim Mangalot",
        "672": "Jardim Maraba",
        "673": "Jardim Maraca",
        "674": "Jardim Maracana",
        "675": "Jardim Marajoara",
        "676": "Jardim Marcel",
        "677": "Jardim Marcelo",
        "678": "Jardim Marciano",
        "679": "Jardim Margarida",
        "680": "Jardim Mariane",
        "681": "Jardim Marilda",
        "682": "Jardim Marilia",
        "683": "Jardim Mariliza",
        "684": "Jardim Marilu",
        "685": "Jardim Marina",
        "686": "Jardim Maringa",
        "687": "Jardim Marisa",
        "688": "Jardim Maristela",
        "689": "Jardim Marpu",
        "690": "Jardim Marquesa",
        "691": "Jardim Martha",
        "692": "Jardim Martini",
        "693": "Jardim Martinica",
        "694": "Jardim Mascarenhas",
        "695": "Jardim Matarazzo",
        "696": "Jardim Mazza",
        "697": "Jardim Meliunas",
        "698": "Jardim Melo",
        "699": "Jardim Mikail",
        "700": "Jardim Mimar",
        "701": "Jardim Miragaia",
        "702": "Jardim Mirante",
        "703": "Jardim Miriam",
        "704": "Jardim Mitsutani",
        "705": "Jardim Modelo",
        "706": "Jardim Monica",
        "707": "Jardim Monjolo",
        "708": "Jardim Moreno",
        "709": "Jardim Morganti",
        "710": "Jardim Morumbi",
        "711": "Jardim Morro Verde",
        "712": "Jardim Monte Alegre",
        "713": "Jardim Monte Azul",
        "714": "Jardim Monte Kemel",
        "715": "Jardim Mutinga",
        "716": "Jardim Myrna",
        "717": "Jardim Nova Brasilia",
        "718": "Jardim Novo Carrao",
        "719": "Jardim Nova Colonia",
        "720": "Jardim Nova Germania",
        "721": "Jardim Nova Guaianazes",
        "722": "Jardim Novo Horizonte",
        "723": "Jardim Nove de Julho",
        "724": "Jardim Nosso Lar",
        "725": "Jardim Novo Mundo",
        "726": "Jardim Novo Parelheiros",
        "727": "Jardim Novo Santo Amaro",
        "728": "Jardim Nossa Senhora do Carmo",
        "729": "Jardim Nagib Salem",
        "730": "Jardim Novo Taboao",
        "731": "Jardim Nova Tereza",
        "732": "Jardim Nadir",
        "733": "Jardim Nair",
        "734": "Jardim Nakamura",
        "735": "Jardim Namba",
        "736": "Jardim Nardini",
        "737": "Jardim Nastari",
        "738": "Jardim Natal",
        "739": "Jardim Naufal",
        "740": "Jardim Nazareth",
        "741": "Jardim Neide",
        "742": "Jardim Neila",
        "743": "Jardim Nelia",
        "744": "Jardim Nelia I",
        "745": "Jardim Nelia II",
        "746": "Jardim Nelia III",
        "747": "Jardim Nelia IV",
        "748": "Jardim Nelia IV (Cod Bai - 18546)",
        "749": "Jardim Nelly",
        "750": "Jardim Nice",
        "751": "Jardim Niteroi",
        "752": "Jardim Nizia",
        "753": "Jardim Noemia",
        "754": "Jardim Nordeste",
        "755": "Jardim Norma",
        "756": "Jardim Noronha",
        "757": "Jardim Odete",
        "758": "Jardim Olinda",
        "759": "Jardim das Oliveiras",
        "760": "Jardim Olympia",
        "761": "Jardim Ondina",
        "762": "Jardim Orbam",
        "763": "Jardim Oriental",
        "764": "Jardim Orion",
        "765": "Jardim Orly",
        "766": "Jardim Ormendina",
        "767": "Jardim Outono",
        "768": "Jardim Paulo Afonso",
        "769": "Jardim Pouso Alegre",
        "770": "Jardim Paulo Borba",
        "771": "Jardim Pedra Branca",
        "772": "Jardim Panorama D'oeste",
        "773": "Jardim Porteira Grande",
        "774": "Jardim Pedro Jose Nunes",
        "775": "Jardim Pereira Leite",
        "776": "Jardim Peri Peri",
        "777": "Jardim Palmares",
        "778": "Jardim das Palmas",
        "779": "Jardim das Palmeiras",
        "780": "Jardim Panorama",
        "781": "Jardim Paqueta",
        "782": "Jardim para",
        "783": "Jardim Paraguacu",
        "784": "Jardim Paris",
        "785": "Jardim Patente Novo",
        "786": "Jardim Patente",
        "787": "Jardim Pauliceia",
        "788": "Jardim Paulista",
        "789": "Jardim Paulistano",
        "790": "Jardim Paulo VI",
        "791": "Jardim das Pedras",
        "792": "Jardim Pedreira",
        "793": "Jardim Penha",
        "794": "Jardim Peri",
        "795": "Jardim Peri Novo",
        "796": "Jardim Perus",
        "797": "Jardim Petisco",
        "798": "Jardim Petropolis",
        "799": "Jardim Picolo",
        "800": "Jardim Pinheiros",
        "801": "Jardim Piqueri",
        "802": "Jardim Piqueroby",
        "803": "Jardim Piracema",
        "804": "Jardim Piracuama",
        "805": "Jardim Pirajussara",
        "806": "Jardim Piratininga",
        "807": "Jardim Pirituba",
        "808": "Jardim Planalto",
        "809": "Jardim Pongilutti",
        "810": "Jardim Popular",
        "811": "Jardim dos Prados",
        "812": "Jardim das Praias",
        "813": "Jardim Presidencia",
        "814": "Jardim Presidente",
        "815": "Jardim Previdencia",
        "816": "Jardim Primavera",
        "817": "Jardim Princesa",
        "818": "Jardim Progresso",
        "819": "Jardim PromisS\xc3\xa2o",
        "820": "Jardim Parque Morumbi",
        "821": "Jardim Prudencia",
        "822": "Jardim Ponte Rasa",
        "823": "Jardim Quarto Centenario",
        "824": "Jardim Quisisana",
        "825": "Jardim Regina Aurea",
        "826": "Jardim Rio Bonito",
        "827": "Jardim Rio Douro",
        "828": "Jardim Rosa Maria",
        "829": "Jardim Rio Pequeno",
        "830": "Jardim Rodolfo Pirani",
        "831": "Jardim Raposo Tavares",
        "832": "Jardim Ramala",
        "833": "Jardim Real",
        "834": "Jardim Recanto do Sol",
        "835": "Jardim Record",
        "836": "Jardim Recreio",
        "837": "Jardim Redencao",
        "838": "Jardim Redil",
        "839": "Jardim Regina",
        "840": "Jardim Regis",
        "841": "Jardim Reimberg",
        "842": "Jardim Remo",
        "843": "Jardim Represa",
        "844": "Jardim Republica",
        "845": "Jardim Ricardo",
        "846": "Jardim Rincao",
        "847": "Jardim Riviera",
        "848": "Jardim Rizzo",
        "849": "Jardim Robru",
        "850": "Jardim Romano",
        "851": "Jardim Roni",
        "852": "Jardim Rosalina",
        "853": "Jardim Rosana",
        "854": "Jardim das Rosas",
        "855": "Jardim Roseli",
        "856": "Jardim Rosider",
        "857": "Jardim Rosina",
        "858": "Jardim Rossin",
        "859": "Jardim Rubilene",
        "860": "Jardim Rubio",
        "861": "Jardim Russo",
        "862": "Jardim Ruth",
        "863": "Jardim Santa Adelia",
        "864": "Jardim Santo Alberto",
        "865": "Jardim Santo Amaro",
        "866": "Jardim Santo Andre",
        "867": "Jardim Santo Antoninho",
        "868": "Jardim Santo Antonio",
        "869": "Jardim S\xc3\xa2o Bento Novo",
        "870": "Jardim Santa Barbara",
        "871": "Jardim S\xc3\xa2o Benedito",
        "872": "Jardim S\xc3\xa2o Bento",
        "873": "Jardim S\xc3\xa2o Bernardo",
        "874": "Jardim Santa Branca",
        "875": "Jardim S\xc3\xa2o Carlos",
        "876": "Jardim Santa Cecilia",
        "877": "Jardim Sagrado Coracao",
        "878": "Jardim S\xc3\xa2o Cristovao",
        "879": "Jardim Santa Cruz",
        "880": "Jardim S\xc3\xa2o Domingos",
        "881": "Jardim Santos Dumont",
        "882": "Jardim Santa Edwiges",
        "883": "Jardim Santa Efigenia",
        "884": "Jardim Santo Elias",
        "885": "Jardim Santa Emilia",
        "886": "Jardim Santa Etelvina",
        "887": "Jardim S\xc3\xa2o Francisco de Assis",
        "888": "Jardim Santa Francisca Cabrini",
        "889": "Jardim Santa Fe",
        "890": "Jardim Santa Filomena",
        "891": "Jardim S\xc3\xa2o Francisco",
        "892": "Jardim S\xc3\xa2o Gabriel",
        "893": "Jardim Santa Gertrudes",
        "894": "Jardim S\xc3\xa2o Goncalo",
        "895": "Jardim Santa Helena",
        "896": "Jardim Santa Ines",
        "897": "Jardim Sonia Inga",
        "898": "Jardim Sabia do Itaim",
        "899": "Jardim S\xc3\xa2o Judas Tadeu",
        "900": "Jardim S\xc3\xa2o Januario",
        "901": "Jardim S\xc3\xa2o Joao",
        "902": "Jardim S\xc3\xa2o Joaquim",
        "903": "Jardim S\xc3\xa2o Jorge",
        "904": "Jardim S\xc3\xa2o Jose",
        "905": "Jardim Santa Josefina",
        "906": "Jardim S Kemel",
        "907": "Jardim S\xc3\xa2o Lourenco",
        "908": "Jardim Santa Lucrecia",
        "909": "Jardim S\xc3\xa2o Luis",
        "910": "Jardim Santa Luisa",
        "911": "Jardim S\xc3\xa2o Manoel",
        "912": "Jardim Santa Marcelina",
        "913": "Jardim Santa Margarida",
        "914": "Jardim Sonia Marly",
        "915": "Jardim S\xc3\xa2o Martinho",
        "916": "Jardim S\xc3\xa2o Mateus",
        "917": "Jardim S\xc3\xa2o Miguel",
        "918": "Jardim Santa Monica",
        "919": "Jardim S\xc3\xa2o Nicolau",
        "920": "Jardim Santo Onofre",
        "921": "Jardim S\xc3\xa2o Paulo",
        "922": "Jardim S\xc3\xa2o Pedro",
        "923": "Jardim S\xc3\xa2o Rafael",
        "924": "Jardim Sonia Regina",
        "925": "Jardim S\xc3\xa2o Remo",
        "926": "Jardim S\xc3\xa2o Ricardo",
        "927": "Jardim Santa Rita",
        "928": "Jardim S\xc3\xa2o Roberto",
        "929": "Jardim S\xc3\xa2o Roque",
        "930": "Jardim Sul S\xc3\xa2o Paulo",
        "931": "Jardim S\xc3\xa2o Saverio",
        "932": "Jardim S\xc3\xa2o Sebastiao",
        "933": "Jardim Sete de Setembro",
        "934": "Jardim S\xc3\xa2o Silvestre",
        "935": "Jardim Silva Teles",
        "936": "Jardim Santa Teresinha",
        "937": "Jardim Santa Tereza",
        "938": "Jardim Santa Terezinha",
        "939": "Jardim S\xc3\xa2o Vicente",
        "940": "Jardim S\xc3\xa2o Vitor",
        "941": "Jardim Santa Zelia",
        "942": "Jardim Sabara",
        "943": "Jardim Samambaia",
        "944": "Jardim Samara",
        "945": "Jardim Samas",
        "946": "Jardim Sandra Maria",
        "947": "Jardim Sandra",
        "948": "Jardim Santana",
        "949": "Jardim Sapopemba",
        "950": "Jardim Sarah",
        "951": "Jardim Satelite",
        "952": "Jardim Saude",
        "953": "Jardim Scaff",
        "954": "Jardim Seckler",
        "955": "Jardim Selma",
        "956": "Jardim Senice",
        "957": "Jardim Sertaozinho",
        "958": "Jardim Shangrila",
        "959": "Jardim Silveira",
        "960": "Jardim Silvia",
        "961": "Jardim Soares",
        "962": "Jardim do Sol",
        "963": "Jardim Solange",
        "964": "Jardim Somara",
        "965": "Jardim Sonia",
        "966": "Jardim Soraia",
        "967": "Jardim Souza",
        "968": "Jardim Santa Maria",
        "969": "Jardim Suzana",
        "970": "Jardim Sydney",
        "971": "Jardim Tres Coracoes",
        "972": "Jardim Teresa Cristina",
        "973": "Jardim Tres Marias",
        "974": "Jardim Tiro ao Pombo",
        "975": "Jardim Taboao",
        "976": "Jardim Taipas",
        "977": "Jardim Tamoio",
        "978": "Jardim Tanay",
        "979": "Jardim Tango",
        "980": "Jardim Tapera",
        "981": "Jardim Taquaral",
        "982": "Jardim Teixeira",
        "983": "Jardim Tenani",
        "984": "Jardim Teresa",
        "985": "Jardim Textil",
        "986": "Jardim Thealia",
        "987": "Jardim Thomaz",
        "988": "Jardim Tiete",
        "989": "Jardim do Tiro",
        "990": "Jardim Toca",
        "991": "Jardim Tremembe",
        "992": "Jardim Triana",
        "993": "Jardim Tricolor",
        "994": "Jardim Tropical",
        "995": "Jardim Trussardi",
        "996": "Jardim Tua",
        "997": "Jardim Tupa",
        "998": "Jardim Tupi",
        "999": "Jardim Turquesa",
        "1000": "Jardim Uberaba",
        "1001": "Jardim Ubirajara",
        "1002": "Jardim Uirapuru",
        "1003": "Jardim Umarizal",
        "1004": "Jardim Umuarama",
        "1005": "Jardim Uniao",
        "1006": "Jardim Universal",
        "1007": "Jardim Universidade",
        "1008": "Jardim Universitario",
        "1009": "Jardim Vista Alegre",
        "1010": "Jardim Virginia Bianca",
        "1011": "Jardim Vilas Boas",
        "1012": "Jardim Vera Cruz",
        "1013": "Jardim Varginha do Itaim",
        "1014": "Jardim Vaz de Lima",
        "1015": "Jardim Vista Linda",
        "1016": "Jardim Vitoria Regia",
        "1017": "Jardim Valquiria",
        "1018": "Jardim Vazani",
        "1019": "Jardim Vergueiro",
        "1020": "Jardim Veronica",
        "1021": "Jardim das Vertentes",
        "1022": "Jardim Viana",
        "1023": "Jardim Vieira",
        "1024": "Jardim Vilma",
        "1025": "Jardim Virginia",
        "1026": "Jardim Vivan",
        "1027": "Jardim Vila Carrao",
        "1028": "Jardim Vila Formosa",
        "1029": "Jardim Vila Mariana",
        "1030": "Jardim Vila Nova Progresso",
        "1031": "Jardim Vale do Ribeira",
        "1032": "Jardim Vale das Virtudes",
        "1033": "Jardim Wilma Flor",
        "1034": "Jardim Wanda",
        "1035": "Jardim Yara",
        "1036": "Jardim Ymay",
        "1037": "Jardim Zaira",
        "1038": "Jardim Zelia",
        "1039": "Jardim Zilda",
        "1040": "Jordanopolis",
        "1041": "Jurubatuba",
        "1042": "Lapa de Baixo",
        "1043": "Lauzane Paulista",
        "1044": "Lageado",
        "1045": "Lapa",
        "1046": "Liberdade",
        "1047": "Limao",
        "1048": "Limoeiro",
        "1049": "Loteamento City Jaragua",
        "1050": "Loteamento Parque das Hortencias",
        "1051": "Luz",
        "1052": "Mata Fria",
        "1053": "Miami Paulista",
        "1054": "Morada do Sol",
        "1055": "Moinho Velho",
        "1056": "Mandaqui",
        "1057": "Maranhao",
        "1058": "Mirandopolis",
        "1059": "Mooca",
        "1060": "Morumbi",
        "1061": "Morro Grande",
        "1062": "Morro do Indio",
        "1063": "Morro dos Ingleses",
        "1064": "Nucleo Carvalho de Araujo",
        "1065": "Nucleo Lageado",
        "1066": "Nova Piraju",
        "1067": "Nossa Senhora do o",
        "1068": "Penha de Franca",
        "1069": "Planalto Paulista",
        "1070": "Promorar Vila Maria",
        "1071": "Pacaembu",
        "1072": "Paineiras do Morumbi",
        "1073": "Parada",
        "1074": "Paraiso",
        "1075": "Paraiso do Morumbi",
        "1076": "Paraisopolis",
        "1077": "Parelheiros",
        "1078": "Pari",
        "1079": "Parada Cinquenta e Sete",
        "1080": "Parada Inglesa",
        "1081": "Parada Quinze",
        "1082": "Pedreira",
        "1083": "Perdizes",
        "1084": "Pereiras",
        "1085": "Perus",
        "1086": "Pinheiros",
        "1087": "Piqueri",
        "1088": "Pirajussara",
        "1089": "Piraporinha",
        "1090": "Pirituba",
        "1091": "Polvilho",
        "1092": "Parque das Cerejeiras",
        "1093": "Praia Azul",
        "1094": "Praia da Lagoa",
        "1095": "Praia do Leblon",
        "1096": "Praias Paulistanas",
        "1097": "Praia Paulistinha",
        "1098": "Parque Leo",
        "1099": "Protendit",
        "1100": "Parque Artur Alvim",
        "1101": "Parque Alves de Lima",
        "1102": "Parque Amazonas",
        "1103": "Parque Amelia",
        "1104": "Parque America",
        "1105": "Parque Anhanguera",
        "1106": "Parque Anhembi",
        "1107": "Parque Arariba",
        "1108": "Parque das Arvores",
        "1109": "Parque Alto do Rio Bonito",
        "1110": "Parque Atlantico",
        "1111": "Parque Boa Esperanca",
        "1112": "Parque Bairro Morumbi",
        "1113": "Parque dos Bancarios",
        "1114": "Parque Belem",
        "1115": "Parque Bologne",
        "1116": "Parque Boturussu",
        "1117": "Parque Brasil",
        "1118": "Parque Bristol",
        "1119": "Parque Casa de Pedra",
        "1120": "Parque Cruzeiro do Sul",
        "1121": "Parque do Carmo",
        "1122": "Parque Central",
        "1123": "Parque Cisper",
        "1124": "Parque Claudia",
        "1125": "Parque Cocaia",
        "1126": "Parque Colonial",
        "1127": "Parque Continental",
        "1128": "Parque Cristina",
        "1129": "Parque Dom Joao Neri",
        "1130": "Parque da Vila Prudente",
        "1131": "Parque das Paineiras",
        "1132": "Parque Deizy",
        "1133": "Parque do Castelo",
        "1134": "Parque Doroteia",
        "1135": "Parque Edu Chaves",
        "1136": "Parque do Engenho",
        "1137": "Parque Esmeralda",
        "1138": "Parque Esperanca",
        "1139": "Parque do Estado",
        "1140": "Parque Fernanda",
        "1141": "Parque Flamengo",
        "1142": "Parque Florestal",
        "1143": "Parque Fongaro",
        "1144": "Parque Grajau",
        "1145": "Parque Guaianazes",
        "1146": "Parque Guarani",
        "1147": "Parque Industrial Tomas Edson",
        "1148": "Parque Ibirapuera",
        "1149": "Parque Imperial",
        "1150": "Parque Independencia",
        "1151": "Parque Industrial",
        "1152": "Parque Ipe",
        "1153": "Parque Itaberaba",
        "1154": "Parque Jabaquara",
        "1155": "Parque Jardim Mirassol",
        "1156": "Parque Luis Mucciolo",
        "1157": "Parque Lagoa Rica",
        "1158": "Parque do Lago",
        "1159": "Parque Lagoinha",
        "1160": "Parque Ligia",
        "1161": "Parque Maria Alice",
        "1162": "Parque Maria Domitila",
        "1163": "Parque Maria Helena",
        "1164": "Parque Maria Luiza",
        "1165": "Parque Monteiro Soares",
        "1166": "Parque Malagoli",
        "1167": "Parque Mandaqui",
        "1168": "Parque Mandi",
        "1169": "Parque da Mooca",
        "1170": "Parque do Morumbi",
        "1171": "Parque Morro Doce",
        "1172": "Parque Muciolo",
        "1173": "Parque Munhoz",
        "1174": "Parque Novo Grajau",
        "1175": "Parque Novo Lar",
        "1176": "Parque Novo Mundo",
        "1177": "Parque Novo Santo Amaro",
        "1178": "Parque Nacoes Unidas",
        "1179": "Parque do Otero",
        "1180": "Parque Pan Americano",
        "1181": "Parque Paineiras",
        "1182": "Parque Paiolzinho",
        "1183": "Parque Paulistano",
        "1184": "Parque Penha",
        "1185": "Parque Pereira",
        "1186": "Parque Peruche",
        "1187": "Parque Petropolis",
        "1188": "Parque Planalto",
        "1189": "Parque Primavera",
        "1190": "Parque dos Principes",
        "1191": "Parque Rodrigues Alves",
        "1192": "Parque Ramos Freitas",
        "1193": "Parque Reboucas",
        "1194": "Parque Recreio",
        "1195": "Parque Regina",
        "1196": "Parque Residencial Cocaia",
        "1197": "Parque Residencial D'abril",
        "1198": "Parque Residencial Julia",
        "1199": "Parque Residencial dos Lagos",
        "1200": "Parque Residencial da Lapa",
        "1201": "Parque Residencial Oratorio",
        "1202": "Parque Residencial Rio Bonito",
        "1203": "Parque Santo Amaro",
        "1204": "Parque Santa Amelia",
        "1205": "Parque Santo Antonio",
        "1206": "Parque Santa Barbara",
        "1207": "Parque Santa Cecilia (Cod Bai - 1",
        "1208": "Parque Santa Cecilia",
        "1209": "Parque Savoi City",
        "1210": "Parque S\xc3\xa2o Domingos",
        "1211": "Parque Santo Eduardo",
        "1212": "Parque S\xc3\xa2o Joaquim",
        "1213": "Parque S\xc3\xa2o Jorge",
        "1214": "Parque S\xc3\xa2o Jose",
        "1215": "Parque S\xc3\xa2o Lourenco",
        "1216": "Parque S\xc3\xa2o Lucas",
        "1217": "Parque S\xc3\xa2o Luis",
        "1218": "Parque Santa Madalena",
        "1219": "Parque S\xc3\xa2o Miguel",
        "1220": "Parque S\xc3\xa2o Paulo",
        "1221": "Parque S\xc3\xa2o Rafael",
        "1222": "Parque Santa Rita",
        "1223": "Parque Sabara",
        "1224": "Parque Santana",
        "1225": "Parque Sevilha",
        "1226": "Parque Sonia",
        "1227": "Parque do Terceiro Lago",
        "1228": "Parque Tomas Saraiva",
        "1229": "Parque Taipas",
        "1230": "Parque Tamari",
        "1231": "Parque Tiete",
        "1232": "Parque Universitario Espirita",
        "1233": "Parque Veloso",
        "1234": "Parque Veredas",
        "1235": "Parque Vitoria",
        "1236": "Parque Vila Maria",
        "1237": "Parque Vila Prudente",
        "1238": "Ponte Pequena",
        "1239": "Ponte Rasa",
        "1240": "Quarta Parada",
        "1241": "Quinta da Paineira",
        "1242": "Rio Bonito",
        "1243": "Real Parque",
        "1244": "Riviera Paulista",
        "1245": "Rio Pequeno",
        "1246": "Raposo Tavares",
        "1247": "Rancho do Abilio",
        "1248": "Rancho Geraldo",
        "1249": "Recanto Ana Maria",
        "1250": "Recanto Campo Belo",
        "1251": "Recanto Marisa",
        "1252": "Recanto Monte Alegre",
        "1253": "Recanto Paraiso",
        "1254": "Recanto Santo Antonio",
        "1255": "Recanto dos Sonhos",
        "1256": "Recanto Verde do Sol",
        "1257": "Republica",
        "1258": "Retiro Morumbi",
        "1259": "Residencial Borore",
        "1260": "Residencial Morumbi",
        "1261": "Residencial Sol Nascente",
        "1262": "Residencial Taipas",
        "1263": "Rolinopolis",
        "1264": "Santo Amaro",
        "1265": "Santa Amelia",
        "1266": "Santa Cecilia",
        "1267": "S\xc3\xa2o Domingos",
        "1268": "Santa Efigenia",
        "1269": "Santa Etelvina",
        "1270": "Santa Ines",
        "1271": "S\xc3\xa2o Joao Climaro",
        "1272": "S\xc3\xa2o Judas",
        "1273": "S\xc3\xa2o Lucas",
        "1274": "S\xc3\xa2o Miguel Paulista",
        "1275": "Santa Maria",
        "1276": "S\xc3\xa2o Mateus",
        "1277": "Sete Praias",
        "1278": "Super Quadra Morumbi",
        "1279": "S\xc3\xa2o Salvador",
        "1280": "Santa Teresinha",
        "1281": "Sacoma",
        "1282": "Santana",
        "1283": "Sapopemba",
        "1284": "Saude",
        "1285": "SE",
        "1286": "Siciliano",
        "1287": "S\xc3\xadtio Areiao",
        "1288": "S\xc3\xadtio Boa Vista",
        "1289": "S\xc3\xadtio Barrocada",
        "1290": "S\xc3\xadtio Botuquara",
        "1291": "S\xc3\xadtio Bufalo",
        "1292": "S\xc3\xadtio Canela Branca",
        "1293": "S\xc3\xadtio Caraguata",
        "1294": "S\xc3\xadtio Cocaia",
        "1295": "S\xc3\xadtio da Figueira",
        "1296": "S\xc3\xadtio Itaberaba I",
        "1297": "S\xc3\xadtio Laredo",
        "1298": "S\xc3\xadtio do Mandaqui",
        "1299": "S\xc3\xadtio Matsumura",
        "1300": "S\xc3\xadtio do Morro",
        "1301": "S\xc3\xadtio Morro Grande",
        "1302": "S\xc3\xadtio Pinheirinho",
        "1303": "S\xc3\xadtio do Piqueri",
        "1304": "S\xc3\xadtio Ponderosa",
        "1305": "S\xc3\xadtio Represa",
        "1306": "S\xc3\xadtio Tapera",
        "1307": "S\xc3\xadtio Vale Verde",
        "1308": "Socorro",
        "1309": "Sumare",
        "1310": "Sumarezinho",
        "1311": "Tres Cruzes",
        "1312": "Terceira DiviS\xc3\xa2o de Interlagos",
        "1313": "Terceira DiviS\xc3\xa2o",
        "1314": "Taipas",
        "1315": "Tambore (Barueri)",
        "1316": "Tatuape",
        "1317": "Tremembe",
        "1318": "Tucuruvi",
        "1319": "Tuparacoera",
        "1320": "Usina Piratininga",
        "1321": "Uniao da Vila Nova",
        "1322": "Umarizal",
        "1323": "Vista Alegre",
        "1324": "Valo Velho",
        "1325": "V\xc3\xa1rzea da Barra Funda",
        "1326": "V\xc3\xa1rzea de Baixo",
        "1327": "Veleiros",
        "1328": "Vila Anglo Brasileira",
        "1329": "Vila Ana Claudia",
        "1330": "Vila Analia Franco",
        "1331": "Vila Agua Funda",
        "1332": "Vila Aparecida Ivone",
        "1333": "Vila Ana Rosa",
        "1334": "Vila Antonio dos Santos",
        "1335": "Vila Abc",
        "1336": "Vila Acre",
        "1337": "Vila Adalgisa",
        "1338": "Vila Ademar",
        "1339": "Vila Agueda",
        "1340": "Vila Aimore",
        "1341": "Vila Alabama",
        "1342": "Vila Alba",
        "1343": "Vila Albano",
        "1344": "Vila Albertina",
        "1345": "Vila Alexandria",
        "1346": "Vila Almeida",
        "1347": "Vila Alpina",
        "1348": "Vila Alteza",
        "1349": "Vila Alzira",
        "1350": "Vila Amalia",
        "1351": "Vila Amelia",
        "1352": "Vila America",
        "1353": "Vila Americana",
        "1354": "Vila Anadir",
        "1355": "Vila Analia",
        "1356": "Vila Anastacio",
        "1357": "Vila Andes",
        "1358": "Vila dos Andradas",
        "1359": "Vila Andrade",
        "1360": "Vila dos Andrades",
        "1361": "Vila Angelica",
        "1362": "Vila Angelina",
        "1363": "Vila Anhanguera",
        "1364": "Vila Antonieta",
        "1365": "Vila Antonina",
        "1366": "Vila Antonio",
        "1367": "Vila Aparecida",
        "1368": "Vila Apoena",
        "1369": "Vila Araguaia",
        "1370": "Vila Arapua",
        "1371": "Vila Arcadia",
        "1372": "Vila Aricanduva",
        "1373": "Vila Ariete",
        "1374": "Vila Arruda",
        "1375": "Vila Augusto",
        "1376": "Vila Aurea",
        "1377": "Vila Aurora",
        "1378": "Vila Azevedo",
        "1379": "Vila Buenos Aires",
        "1380": "Vila Bela Alianca",
        "1381": "Vila Belo Horizonte",
        "1382": "Vila Bom Jardim",
        "1383": "Vila Brasilio Machado",
        "1384": "Vila Bancaria Munhoz",
        "1385": "Vila Bonilha Nova",
        "1386": "Vila Bela do Sapopemba",
        "1387": "Vila Bela Vista",
        "1388": "Vila Babilonia",
        "1389": "Vila Baby",
        "1390": "Vila Bancaria",
        "1391": "Vila Bandeirantes",
        "1392": "Vila Barbara",
        "1393": "Vila Barbosa",
        "1394": "Vila Barreto",
        "1395": "Vila Baruel",
        "1396": "Vila Basileia",
        "1397": "Vila Bauab",
        "1398": "Vila Beatriz",
        "1399": "Vila Bela",
        "1400": "Vila das Belezas",
        "1401": "Vila Bertioga",
        "1402": "Vila Bianca",
        "1403": "Vila Boacava",
        "1404": "Vila Bonilha",
        "1405": "Vila Borges",
        "1406": "Vila do Bosque",
        "1407": "Vila Botoni",
        "1408": "Vila Bozzini",
        "1409": "Vila Brasil",
        "1410": "Vila Brasilandia",
        "1411": "Vila Brasilia",
        "1412": "Vila Brasilina",
        "1413": "Vila Buarque",
        "1414": "Vila Buriti",
        "1415": "Vila Butanta",
        "1416": "Vila Cruz das Almas",
        "1417": "Vila Cunha Bueno",
        "1418": "Vila Carlos de Campos",
        "1419": "Vila Cardoso Franco",
        "1420": "Vila Chica Luisa",
        "1421": "Vila Costa Melo",
        "1422": "Vila Cruzeiro Novo",
        "1423": "Vila Conde do Pinhal",
        "1424": "Vila Curuca Velha",
        "1425": "Vila Cachoeira",
        "1426": "Vila Cachoeirinha",
        "1427": "Vila Caicara",
        "1428": "Vila Caiuba",
        "1429": "Vila Caju",
        "1430": "Vila California",
        "1431": "Vila Calu",
        "1432": "Vila Campanela",
        "1433": "Vila Campestre",
        "1434": "Vila Canero",
        "1435": "Vila Capela",
        "1436": "Vila Caraguata",
        "1437": "Vila Carbone",
        "1438": "Vila Cardoso",
        "1439": "Vila Carioca",
        "1440": "Vila Carmem",
        "1441": "Vila Carmosina",
        "1442": "Vila Carolina",
        "1443": "Vila Carrao",
        "1444": "Vila Castelo",
        "1445": "Vila Castro",
        "1446": "Vila Catupia",
        "1447": "Vila Cavaton",
        "1448": "Vila Caxambu",
        "1449": "Vila Celeste",
        "1450": "Vila Centenario",
        "1451": "Vila Central",
        "1452": "Vila Chabilandia",
        "1453": "Vila Chalot",
        "1454": "Vila Charlote",
        "1455": "Vila Chavantes",
        "1456": "Vila Chuca",
        "1457": "Vila Cisper",
        "1458": "Vila Clara",
        "1459": "Vila Clarice",
        "1460": "Vila Claudia",
        "1461": "Vila Clelia",
        "1462": "Vila Clementino",
        "1463": "Vila Cleonice",
        "1464": "Vila Comercial",
        "1465": "Vila Conceicao",
        "1466": "Vila Congonhas",
        "1467": "Vila Constancia",
        "1468": "Vila Continental",
        "1469": "Vila Corberi",
        "1470": "Vila Cordeiro",
        "1471": "Vila Cosmopolita",
        "1472": "Vila Campo Grande",
        "1473": "Vila Cristalia",
        "1474": "Vila Cruzeiro",
        "1475": "Vila Curuca",
        "1476": "Vila Dona Augusta",
        "1477": "Vila Danubio Azul",
        "1478": "Vila Doutor Eiras",
        "1479": "Vila Dom Jose",
        "1480": "Vila Dona Meta",
        "1481": "Vila Divina Pastora",
        "1482": "Vila Dom Pedro I",
        "1483": "Vila Dom Pedro II",
        "1484": "Vila Dona Sara",
        "1485": "Vila Dalila",
        "1486": "Vila Dalva",
        "1487": "Vila Damaceno",
        "1488": "Vila Darli",
        "1489": "Vila Deodoro",
        "1490": "Vila Dinorah",
        "1491": "Vila Dionisia",
        "1492": "Vila Diva",
        "1493": "Vila do Castelo",
        "1494": "Vila Domitila",
        "1495": "Vila Dorna",
        "1496": "Vila Duarte",
        "1497": "Vila Elias Nigri",
        "1498": "Vila Ede",
        "1499": "Vila Elba",
        "1500": "Vila Eliana",
        "1501": "Vila Elida",
        "1502": "Vila Eliete",
        "1503": "Vila Elisio",
        "1504": "Vila Elvira",
        "1505": "Vila Elze",
        "1506": "Vila Ema",
        "1507": "Vila Emir",
        "1508": "Vila do Encontro",
        "1509": "Vila Erna",
        "1510": "Vila Ernesto",
        "1511": "Vila Escolar",
        "1512": "Vila Esmeralda",
        "1513": "Vila Espanhola",
        "1514": "Vila Esperanca",
        "1515": "Vila Ester",
        "1516": "Vila Euthalia",
        "1517": "Vila Fiat Lux",
        "1518": "Vila Firmiano Pinto",
        "1519": "Vila Fidelis Ribeiro",
        "1520": "Vila Fachini",
        "1521": "Vila Fanton",
        "1522": "Vila Fatima",
        "1523": "Vila Fazzeoni",
        "1524": "Vila Feliz",
        "1525": "Vila Fernandes",
        "1526": "Vila Fidalgo",
        "1527": "Vila Flavia",
        "1528": "Vila Formosa",
        "1529": "Vila Franca",
        "1530": "Vila Franci",
        "1531": "Vila Francos",
        "1532": "Vila Friburgo",
        "1533": "Vila Frugoli",
        "1534": "Vila Fukuya",
        "1535": "Vila Gomes Cardim",
        "1536": "Vila Gabriel",
        "1537": "Vila Gea",
        "1538": "Vila Germaine",
        "1539": "Vila Germinal",
        "1540": "Vila Gertrudes",
        "1541": "Vila Gil",
        "1542": "Vila Gilda",
        "1543": "Vila Giordano",
        "1544": "Vila Gomes",
        "1545": "Vila Gouveia",
        "1546": "Vila Graciosa",
        "1547": "Vila Granada",
        "1548": "Vila Graziela",
        "1549": "Vila Guaca",
        "1550": "Vila Guacuri",
        "1551": "Vila Guaraciaba",
        "1552": "Vila Guarani",
        "1553": "Vila Guedes",
        "1554": "Vila Guilherme",
        "1555": "Vila Guilhermina",
        "1556": "Vila Gumercindo",
        "1557": "Vila Gustavo",
        "1558": "Vila Hadad",
        "1559": "Vila Hamburguesa",
        "1560": "Vila Hebe",
        "1561": "Vila Helena",
        "1562": "Vila Heliopolis",
        "1563": "Vila Herminia",
        "1564": "Vila Homero",
        "1565": "Vila Hungaresa",
        "1566": "Vila Irmaos Arnoni",
        "1567": "Vila Isolina Mazzei",
        "1568": "Vila Icarai",
        "1569": "Vila Ida",
        "1570": "Vila Iguacu",
        "1571": "Vila Imperio",
        "1572": "Vila Inacio",
        "1573": "Vila Inah",
        "1574": "Vila Independencia",
        "1575": "Vila Indiana",
        "1576": "Vila Industrial",
        "1577": "Vila Inglesa",
        "1578": "Vila Invernada",
        "1579": "Vila Iorio",
        "1580": "Vila Ipojuca",
        "1581": "Vila Iracema",
        "1582": "Vila Irene",
        "1583": "Vila Isa",
        "1584": "Vila Isabel",
        "1585": "Vila Isolina",
        "1586": "Vila Itaberaba",
        "1587": "Vila Itaim",
        "1588": "Vila Ivg",
        "1589": "Vila Ivone",
        "1590": "Vila Joao Batista",
        "1591": "Vila Julio Cesar",
        "1592": "Vila Jacui",
        "1593": "Vila Jaguara",
        "1594": "Vila Jaguari",
        "1595": "Vila Jaragua",
        "1596": "Vila Jardim Zoologico",
        "1597": "Vila Joaniza",
        "1598": "Vila Judith",
        "1599": "Vila Julio",
        "1600": "Vila Jurema",
        "1601": "Vila Jussara",
        "1602": "Vila Klaunig",
        "1603": "Vila Lucia Elvira",
        "1604": "Vila Lar Nacional",
        "1605": "Vila Lageado",
        "1606": "Vila Lais",
        "1607": "Vila Leme",
        "1608": "Vila Leonor",
        "1609": "Vila Leopoldina",
        "1610": "Vila Libanesa",
        "1611": "Vila Lisboa",
        "1612": "Vila Liviero",
        "1613": "Vila Londrina",
        "1614": "Vila Lourdes",
        "1615": "Vila Lucia",
        "1616": "Vila Maria Alta",
        "1617": "Vila Maria Augusta",
        "1618": "Vila Maria Baixa",
        "1619": "Vila Maria Eugenia",
        "1620": "Vila Maria Luisa",
        "1621": "Vila Mariza Mazzei",
        "1622": "Vila Maria Trindade",
        "1623": "Vila Moinho Velho",
        "1624": "Vila Maria Zelia",
        "1625": "Vila Macedopolis",
        "1626": "Vila Madalena",
        "1627": "Vila Mafra",
        "1628": "Vila Malvina",
        "1629": "Vila Mangalot",
        "1630": "Vila Mara",
        "1631": "Vila Maracana",
        "1632": "Vila Marari",
        "1633": "Vila Marcelo",
        "1634": "Vila Marconi",
        "1635": "Vila Margareth",
        "1636": "Vila Margarida",
        "1637": "Vila Maria",
        "1638": "Vila Mariana",
        "1639": "Vila Marieta",
        "1640": "Vila Marilena",
        "1641": "Vila Marina",
        "1642": "Vila Maringa",
        "1643": "Vila Marte",
        "1644": "Vila Mascote",
        "1645": "Vila Matias",
        "1646": "Vila Matilde",
        "1647": "Vila Mazzei",
        "1648": "Vila Medeiros",
        "1649": "Vila Mendes",
        "1650": "Vila Mercedes",
        "1651": "Vila das Merces",
        "1652": "Vila Mesquita",
        "1653": "Vila Miami",
        "1654": "Vila Michelina",
        "1655": "Vila dos Minerios",
        "1656": "Vila Minerva",
        "1657": "Vila Mira",
        "1658": "Vila Mirante",
        "1659": "Vila Miriam",
        "1660": "Vila Mirim",
        "1661": "Vila Missionaria",
        "1662": "Vila Moderna",
        "1663": "Vila Monumento",
        "1664": "Vila Moraes",
        "1665": "Vila Moreira",
        "1666": "Vila Morgadouro",
        "1667": "Vila Morse",
        "1668": "Vila Morumbi",
        "1669": "Vila Morro Grande",
        "1670": "Vila Monte Alegre",
        "1671": "Vila Monte Santo",
        "1672": "Vila Nova Alba",
        "1673": "Vila Nova das Belezas",
        "1674": "Vila Nova Cachoeirinha",
        "1675": "Vila Nova Caledonia",
        "1676": "Vila Nova Carolina",
        "1677": "Vila Nova Conceicao",
        "1678": "Vila Nova Curuca",
        "1679": "Vila Nova Galvao",
        "1680": "Vila Nova Jaragua",
        "1681": "Vila Nova Manchester",
        "1682": "Vila Nova Mazzei",
        "1683": "Vila Nitro Operaria",
        "1684": "Vila Nova Pauliceia",
        "1685": "Vila Nova Perus",
        "1686": "Vila Nova Pirajussara",
        "1687": "Vila Nitro Quimica",
        "1688": "Vila Nossa Senhora Aparecida",
        "1689": "Vila Nossa Senhora da Conceicao",
        "1690": "Vila Nossa Senhora do Libano",
        "1691": "Vila Nova S\xc3\xa2o Miguel",
        "1692": "Vila Nossa Senhora do Retiro",
        "1693": "Vila Nova Savoia",
        "1694": "Vila Nova Teresa",
        "1695": "Vila Nova Uniao",
        "1696": "Vila Nova Utinga",
        "1697": "Vila Nova York",
        "1698": "Vila Nair",
        "1699": "Vila Nancy",
        "1700": "Vila Nascente",
        "1701": "Vila Natal",
        "1702": "Vila Natalia",
        "1703": "Vila Neila",
        "1704": "Vila Nelson",
        "1705": "Vila Nhocune",
        "1706": "Vila Nilo",
        "1707": "Vila Nilva",
        "1708": "Vila Nina",
        "1709": "Vila Nivi",
        "1710": "Vila Noca",
        "1711": "Vila Nogueira",
        "1712": "Vila Norma",
        "1713": "Vila Nova",
        "1714": "Vila Odete",
        "1715": "Vila Olga",
        "1716": "Vila Olimpia",
        "1717": "Vila Olinda",
        "1718": "Vila Oratorio",
        "1719": "Vila Pereira Barreto",
        "1720": "Vila Pedra Branca",
        "1721": "Vila Pereira Cerca",
        "1722": "Vila Princesa Isabel",
        "1723": "Vila Primeiro de Outubro",
        "1724": "Vila Paulo Silas",
        "1725": "Vila Paiva",
        "1726": "Vila dos Palmares",
        "1727": "Vila Palmeiras",
        "1728": "Vila Paranagua",
        "1729": "Vila Patrimonial",
        "1730": "Vila Pauliceia",
        "1731": "Vila Paulina",
        "1732": "Vila Paulista",
        "1733": "Vila da Paz",
        "1734": "Vila Pedroso",
        "1735": "Vila Penteado",
        "1736": "Vila Perus",
        "1737": "Vila Piaui",
        "1738": "Vila Picinin",
        "1739": "Vila Pierina",
        "1740": "Vila Piracicaba",
        "1741": "Vila Pirajussara",
        "1742": "Vila Pirituba",
        "1743": "Vila Pita",
        "1744": "Vila Plana",
        "1745": "Vila Paulistana",
        "1746": "Vila Paulistania",
        "1747": "Vila Polopoli",
        "1748": "Vila Pompeia",
        "1749": "Vila Popular",
        "1750": "Vila Portugal",
        "1751": "Vila Portuguesa",
        "1752": "Vila Prado",
        "1753": "Vila Praia",
        "1754": "Vila Prel",
        "1755": "Vila Primavera",
        "1756": "Vila Progredior",
        "1757": "Vila Progresso",
        "1758": "Vila Parque Jabaquara",
        "1759": "Vila Prudente",
        "1760": "Vila Ponte Rasa",
        "1761": "Vila Quarto Centenario",
        "1762": "Vila Quintana",
        "1763": "Vila Rancho Alegre",
        "1764": "Vila Rui Barbosa",
        "1765": "Vila Ribeiro de Barros",
        "1766": "Vila Rio Branco",
        "1767": "Vila Regente Feijo",
        "1768": "Vila Rosa Molla",
        "1769": "Vila Ramos",
        "1770": "Vila Raquel",
        "1771": "Vila Re",
        "1772": "Vila Regina",
        "1773": "Vila Reis",
        "1774": "Vila dos Remedios",
        "1775": "Vila Remo",
        "1776": "Vila Renato",
        "1777": "Vila Represa",
        "1778": "Vila Rica",
        "1779": "Vila Robertina",
        "1780": "Vila Rodrigues",
        "1781": "Vila Romana",
        "1782": "Vila Romano",
        "1783": "Vila Romero",
        "1784": "Vila Roque",
        "1785": "Vila Rosaria",
        "1786": "Vila Roschel",
        "1787": "Vila Rosina",
        "1788": "Vila Rubi",
        "1789": "Vila Santo Antonio",
        "1790": "Vila S\xc3\xa2o Camilo",
        "1791": "Vila Santa Catarina",
        "1792": "Vila Santa Clara",
        "1793": "Vila Santa Cruz",
        "1794": "Vila Santa Delfina",
        "1795": "Vila S\xc3\xa2o Domingos",
        "1796": "Vila Santo Estevam Reis",
        "1797": "Vila Santa Edwiges",
        "1798": "Vila Santo Estefano",
        "1799": "Vila Santo Estevao",
        "1800": "Vila Santa Eulalia",
        "1801": "Vila S\xc3\xa2o Francisco",
        "1802": "Vila S\xc3\xa2o Geraldo",
        "1803": "Vila Santo Henrique",
        "1804": "Vila Santa Ines",
        "1805": "Vila Santa Isabel",
        "1806": "Vila S\xc3\xa2o Jose",
        "1807": "Vila S\xc3\xa2o Judas",
        "1808": "Vila Santa Lucia",
        "1809": "Vila S\xc3\xa2o Luis",
        "1810": "Vila Santa Maria",
        "1811": "Vila S\xc3\xa2o Nicolau",
        "1812": "Vila S\xc3\xa2o Paulo",
        "1813": "Vila S\xc3\xa2o Pedro",
        "1814": "Vila S\xc3\xa2o Sebastiao",
        "1815": "Vila S\xc3\xa2o Silvestre",
        "1816": "Vila Silva Teles",
        "1817": "Vila Santa Teresa",
        "1818": "Vila Santa Teresinha",
        "1819": "Vila Santa Terezinha",
        "1820": "Vila S\xc3\xa2o Vicente",
        "1821": "Vila Santa Virginia",
        "1822": "Vila Sabrina",
        "1823": "Vila Salete",
        "1824": "Vila Sampaio",
        "1825": "Vila Santana",
        "1826": "Vila Santista",
        "1827": "Vila Santos",
        "1828": "Vila Sapopemba",
        "1829": "Vila Sara",
        "1830": "Vila da Saude",
        "1831": "Vila Savoy",
        "1832": "Vila Seabra",
        "1833": "Vila Sergio",
        "1834": "Vila Serralheiro",
        "1835": "Vila Silveira",
        "1836": "Vila Silvia",
        "1837": "Vila Simone",
        "1838": "Vila Sinha",
        "1839": "Vila Siqueira",
        "1840": "Vila Sirene",
        "1841": "Vila Siria",
        "1842": "Vila Socorro",
        "1843": "Vila Sofia",
        "1844": "Vila Sol",
        "1845": "Vila Solange",
        "1846": "Vila Sonia",
        "1847": "Vila Souza",
        "1848": "Vila Stela",
        "1849": "Vila Suica",
        "1850": "Vila Sulina",
        "1851": "Vila Suzana",
        "1852": "Vila Taiau",
        "1853": "Vila Talarico",
        "1854": "Vila Taquari",
        "1855": "Vila Teresinha",
        "1856": "Vila Tiradentes",
        "1857": "Vila Tolstoi",
        "1858": "Vila Tramontano",
        "1859": "Vila Uberabinha",
        "1860": "Vila Uniao",
        "1861": "Vila Universitaria",
        "1862": "Vila Ursulina",
        "1863": "Vila Vitorio Mazzei",
        "1864": "Vila Valdemar",
        "1865": "Vila Vasconcelos",
        "1866": "Vila Vera",
        "1867": "Vila Verde",
        "1868": "Vila Vermelha",
        "1869": "Vila Vessoni",
        "1870": "Vila Virginia",
        "1871": "Vila Vitoria",
        "1872": "Vila Yara",
        "1873": "Vila Yolanda",
        "1874": "Vila Zat",
        "1875": "Vila Zefira",
        "1876": "Vila Zelina",
        "1877": "Vila Zilda",
        "1878": "Vila Zulmira",
        "9999": "Outros Munic\xc3\xadpios de S\xc3\xa2o Paulo",
          "-1": "Ignorado"

    }
    d = {int(k):  unicode(v, 'utf8') for k, v in bairros.items()}
    return d
