# -*- coding:  utf-8 -*-

def distrito_sp_dic():
    distritos = {
        0: "Fora do Estado de S\xc3\xa2o Paulo",
        1: "Agua Rasa",
        2: "Alto de Pinheiros",
        3: "Anhanguera",
        4: "Aricanduva",
        5: "Artur Alvim",
        6: "Barra Funda",
        7: "Bela Vista",
        8: "Belem",
        9: "Bom Retiro",
        10: "Bras",
        11: "Brasilandia",
        12: "Butanta",
        13: "Cambuci",
        14: "Campo Belo",
        15: "Campo Grande",
        16: "Campo Limpo",
        17: "Cangaiba",
        18: "Capao Redondo",
        19: "Carrao",
        20: "Casa Verde",
        21: "Cidade Ademar",
        22: "Cidade Dutra",
        23: "Cidade Lider",
        24: "Cidade Tiradentes",
        25: "Consolacao",
        26: "Cursino",
        27: "Ermelino Matarazzo",
        28: "Freguesia do \xc3\x93",
        29: "Grajau",
        30: "Guaianazes",
        31: "Iguatemi",
        32: "Ipiranga",
        33: "Itaim Bibi",
        34: "Itaim Paulista",
        35: "Itaquera",
        36: "Jabaquara",
        37: "Jacana",
        38: "Jaguara",
        39: "Jaguare",
        40: "Jaragua",
        41: "Jardim Angela",
        42: "Jardim Helena",
        43: "Jardim Paulista",
        44: "Jose Bonifacio",
        45: "Lajeado",
        46: "Lapa",
        47: "Liberdade",
        48: "Limao",
        49: "Mandaqui",
        50: "Marsilac",
        51: "Moema",
        52: "Mooca",
        53: "Morumbi",
        54: "Nova Cachoeirinha",
        55: "Parelheiros",
        56: "Pari",
        57: "Parque do Carmo",
        58: "Pedreira",
        59: "Penha",
        60: "Perdizes",
        61: "Perus",
        62: "Pinheiros",
        63: "Pirituba",
        64: "Ponte Rasa",
        65: "Raposo Tavares",
        66: "Republica",
        67: "Rio Pequeno",
        68: "Sacoma",
        69: "Santa Cecilia",
        70: "Santana",
        71: "Santo Amaro",
        72: "Sao Domingos",
        73: "Sao Lucas",
        74: "Sao Luis",
        75: "Sao Mateus",
        76: "Sao Miguel",
        77: "Sao Rafael",
        78: "Sapopemba",
        79: "Saude",
        80: "S\xc3\xa9",
        81: "Socorro",
        82: "Tatuape",
        83: "Tremembe",
        84: "Tucuruvi",
        85: "Vila Andrade",
        86: "Vila Curuca",
        87: "Vila Formosa",
        88: "Vila Jacui",
        89: "Vila Leopoldina",
        90: "Vila Maria",
        91: "Vila Guilherme",
        92: "Vila Mariana",
        93: "Vila Matilde",
        94: "Vila Medeiros",
        95: "Vila Prudente",
        96: "Vila Sonia",
        99: "Outros Munic\xc3\xadpios de S\xc3\xa2o Paulo",
        -1: "Ignorado"

    }

    d = {k: unicode(v, 'utf8') for k, v in distritos.items()}

    return d
